version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped

  web:
    image: 'jury/p0ck37'
    container_name: jury-p0ck37
    restart: unless-stopped
    ports:
      - 8080:8080
    links:
      - mongodb
