/* This file is auto-generated by brotoc.
 * It's like protoc, but much more cooler. */
#ifndef _LINK_HPP_
#define _LINK_HPP_
#include "broto.hpp"
namespace brotobuf {
class Link : public _AbstractMessage {
public:
  unsigned long long type;
  std::string value;
  Link();
  void serialize(OutputStream &stream) const;
  void serialize(OutputStream &&stream) const;
  void deserialize(InputStream &stream);
  void deserialize(InputStream &&stream);

private:
  void serialize_type(OutputStream &stream) const;
  void serialize_value(OutputStream &stream) const;
};
} // namespace brotobuf
#endif