/* This file is auto-generated by brotoc.
 * It's like protoc, but much more cooler. */
#ifndef _PERSON_HPP_
#define _PERSON_HPP_
#include "broto.hpp"
#include <optional>
#include <vector>
namespace brotobuf {
class Person : public _AbstractMessage {
public:
  unsigned long long birth_date;
  unsigned long long death_date;
  std::string name;
  std::vector<Person> parents;
  Person();
  void serialize(OutputStream &stream) const;
  void serialize(OutputStream &&stream) const;
  void deserialize(InputStream &stream);
  void deserialize(InputStream &&stream);

private:
  std::vector<Person>::iterator _parents_iterator;
  void serialize_birth_date(OutputStream &stream) const;
  void serialize_death_date(OutputStream &stream) const;
  void serialize_name(OutputStream &stream) const;
  void serialize_parents(OutputStream &stream) const;
};
} // namespace brotobuf
#endif