---

- name: Copy docker image
  copy:
    src: '../jury_services/oauth/oauth.tar'
    dest: '/root'
  register: archive

- name: Load docker image
  community.docker.docker_image:
    name: jury/oauth
    tag: latest
    load_path: /root/oauth.tar
    source: load
    force_source: yes
  when: archive.changed

- name: Copy docker-compose.yml
  copy:
    src: '../jury_services/oauth/docker-compose.yml'
    dest: '/root/docker-compose.oauth.yml'

- name: Create and start services
  community.docker.docker_compose:
    project_src: /root/
    files:
      - docker-compose.oauth.yml
  register: output

- ansible.builtin.debug:
    var: output

- name: Cleanup docker
  community.docker.docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes
