version: '3.4'

volumes:
  postgres-data:


services:
  postgres:
    image: postgres:14.1
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data/postgresql/scripts:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    env_file:
      - env/postgresql.env

  database:
    image: pgbouncer/pgbouncer
    depends_on:
      - postgres
    volumes:
      - ./data/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    restart: unless-stopped
    env_file:
      - env/pgbouncer.env

  genealogy:
    build: .
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - ./.keys:/app/keys
    ports:
      - "8888:8888"
