version: '3.4'

volumes:
  postgres-data:
  keys:


services:
  postgres:
    image: postgres:14.1
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data/postgresql/scripts:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    env_file:
      - env/postgresql.env

  database:
    image: pgbouncer/pgbouncer
    depends_on:
      - postgres
    volumes:
      - ./data/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    restart: unless-stopped
    env_file:
      - env/pgbouncer.env

  nginx:
    image: nginx:latest
    depends_on:
      - genealogy
    volumes:
      - ./data/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/static:/static:ro
    ports:
      - "8888:8888"

  genealogy:
    build: .
    depends_on:
      - database
    restart: unless-stopped
    read_only: true
    user: "1000:1000"
    volumes:
      - keys:/app/keys
    environment:
      DATABASE: "host=database port=6432 dbname=genealogy user=genealogy password=genealogy"

