version: '3'
services:
  mp:
    container_name: mp
    restart: unless-stopped
    build: .
    depends_on:
      - "opensearch-node1"
    ports:
      - 80:80
    volumes:
      - ./state:/app/state
      - ./settings:/settings
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    restart: unless-stopped
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - plugins.security.ssl.http.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./opensearch/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
      - ./opensearch/config.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml

volumes:
  opensearch-data1:
