version: '2.1'
services:
  fs:
    build: .
    restart: unless-stopped
    pids_limit: 500
    image: fs
    volumes:
      - ./src:/home/fs
    ports:
      - 7777:7777
    ulimits:
       nproc: 5000
       nofile:
          soft: 20000
          hard: 40000
