#ifndef _HTTP_STATUS_CODE_HPP_

#define _HTTP_STATUS_CODE_HPP_

enum HttpStatusCode {
    OK = 200,
    CREATED = 201,

    MOVED_PERMANENTLY = 301,
    FOUND = 302,
    NOT_MODIFIED = 304,   

    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    METHOD_NOT_ALLOWED = 405,
    REQUEST_TIMEOUT = 408,
    CONFLICT = 409,
    LENGTH_REQUIRED = 411,
    PRECONDITION_FAILED = 412,
    I_M_A_TEAPOT = 418,
    TOO_MANY_REQUESTS = 429,

    INTERNAL_SERVER_ERROR = 500,
};

#endif