version: '3'
services:
  oauth:
    image: 'jury/oauth'
    container_name: oauth
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - data-protection-volume:/root/.aspnet/DataProtection-Keys

volumes:
  data-protection-volume:
