- hosts: checkers, master
  tasks:
  - name: sync catalog
    synchronize:
      src: "../checkers"
      dest: "{{ cs_dir }}"
    tags: sync

  - name: cs to docker
    user:
      name: "{{ cs_user }}"
      groups: docker
      append: yes

  - name: checkers owner
    file:
      path: "{{ cs_dir }}/checkers"
      owner: "{{ cs_user }}"
      group: "{{ cs_user }}"
      recurse: yes
    tags: sync

  - name: install sys deps
    apt:
      name:
        - g++
        - make
        - libssl-dev
        - python3-pip
        - libpython3.9-dev
      install_recommends: no

  - name: dotnet repo keys
    apt:
      deb: https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb

  - name: install net-sdk
    apt:
      name:
        - dotnet-sdk-5.0
        - dotnet-sdk-6.0
      state: latest
      update_cache: yes

  - name: build timecapsule checker
    shell:
    args:
      cmd: dotnet publish -c Release
      chdir: "{{ cs_dir }}/checkers/timecapsule/src"
    become: yes
    become_user: "{{ cs_user }}"

  - name: build mp checker
    shell:
    args:
      cmd: dotnet publish -c Release
      chdir: "{{ cs_dir }}/checkers/mp/src"
    become: yes
    become_user: "{{ cs_user }}"

  - name: build cells checker
    shell:
    args:
      cmd: docker build . -t "cells_container"
      chdir: "{{ cs_dir }}/checkers/cells"
    become: yes
    become_user: "{{ cs_user }}"

  - name: python deps
    pip:
      executable: pip3
      requirements: "{{ cs_dir }}/checkers/{{ item }}/requirements.txt"
    loop:
      - genealogy
      - forvolution
