# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: caas.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='caas.proto',
  package='caas',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ncaas.proto\x12\x04\x63\x61\x61s\"<\n\x0e\x45nqueueRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\"\"\n\x0f\x45nqueueResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\"/\n\rResultRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\x05\"7\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"C\n\x13UserRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\"\"\n\x11UserRegisterReply\x12\r\n\x05token\x18\x01 \x01(\t\" \n\x0fUserInfoRequest\x12\r\n\x05token\x18\x01 \x01(\t\"=\n\rUserInfoReply\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t2~\n\x04user\x12@\n\x08Register\x12\x19.caas.UserRegisterRequest\x1a\x17.caas.UserRegisterReply\"\x00\x12\x34\n\x04Info\x12\x15.caas.UserInfoRequest\x1a\x13.caas.UserInfoReply\"\x00\x32r\n\x04\x63url\x12\x38\n\x07\x45nqueue\x12\x14.caas.EnqueueRequest\x1a\x15.caas.EnqueueResponse\"\x00\x12\x30\n\tGetReulst\x12\x13.caas.ResultRequest\x1a\x0c.caas.Result\"\x00\x62\x06proto3'
)




_ENQUEUEREQUEST = _descriptor.Descriptor(
  name='EnqueueRequest',
  full_name='caas.EnqueueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='caas.EnqueueRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method', full_name='caas.EnqueueRequest.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='caas.EnqueueRequest.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=80,
)


_ENQUEUERESPONSE = _descriptor.Descriptor(
  name='EnqueueResponse',
  full_name='caas.EnqueueResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='caas.EnqueueResponse.task_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=116,
)


_RESULTREQUEST = _descriptor.Descriptor(
  name='ResultRequest',
  full_name='caas.ResultRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='caas.ResultRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='caas.ResultRequest.task_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=165,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='caas.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='caas.Result.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='caas.Result.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='caas.Result.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=222,
)


_USERREGISTERREQUEST = _descriptor.Descriptor(
  name='UserRegisterRequest',
  full_name='caas.UserRegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='caas.UserRegisterRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='caas.UserRegisterRequest.image', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment', full_name='caas.UserRegisterRequest.comment', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=291,
)


_USERREGISTERREPLY = _descriptor.Descriptor(
  name='UserRegisterReply',
  full_name='caas.UserRegisterReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='caas.UserRegisterReply.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=327,
)


_USERINFOREQUEST = _descriptor.Descriptor(
  name='UserInfoRequest',
  full_name='caas.UserInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='caas.UserInfoRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=361,
)


_USERINFOREPLY = _descriptor.Descriptor(
  name='UserInfoReply',
  full_name='caas.UserInfoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='caas.UserInfoReply.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='caas.UserInfoReply.image', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment', full_name='caas.UserInfoReply.comment', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=424,
)

DESCRIPTOR.message_types_by_name['EnqueueRequest'] = _ENQUEUEREQUEST
DESCRIPTOR.message_types_by_name['EnqueueResponse'] = _ENQUEUERESPONSE
DESCRIPTOR.message_types_by_name['ResultRequest'] = _RESULTREQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['UserRegisterRequest'] = _USERREGISTERREQUEST
DESCRIPTOR.message_types_by_name['UserRegisterReply'] = _USERREGISTERREPLY
DESCRIPTOR.message_types_by_name['UserInfoRequest'] = _USERINFOREQUEST
DESCRIPTOR.message_types_by_name['UserInfoReply'] = _USERINFOREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnqueueRequest = _reflection.GeneratedProtocolMessageType('EnqueueRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENQUEUEREQUEST,
  '__module__' : 'caas_pb2'
  # @@protoc_insertion_point(class_scope:caas.EnqueueRequest)
  })
_sym_db.RegisterMessage(EnqueueRequest)

EnqueueResponse = _reflection.GeneratedProtocolMessageType('EnqueueResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENQUEUERESPONSE,
  '__module__' : 'caas_pb2'
  # @@protoc_insertion_point(class_scope:caas.EnqueueResponse)
  })
_sym_db.RegisterMessage(EnqueueResponse)

ResultRequest = _reflection.GeneratedProtocolMessageType('ResultRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESULTREQUEST,
  '__module__' : 'caas_pb2'
  # @@protoc_insertion_point(class_scope:caas.ResultRequest)
  })
_sym_db.RegisterMessage(ResultRequest)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'caas_pb2'
  # @@protoc_insertion_point(class_scope:caas.Result)
  })
_sym_db.RegisterMessage(Result)

UserRegisterRequest = _reflection.GeneratedProtocolMessageType('UserRegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREGISTERREQUEST,
  '__module__' : 'caas_pb2'
  # @@protoc_insertion_point(class_scope:caas.UserRegisterRequest)
  })
_sym_db.RegisterMessage(UserRegisterRequest)

UserRegisterReply = _reflection.GeneratedProtocolMessageType('UserRegisterReply', (_message.Message,), {
  'DESCRIPTOR' : _USERREGISTERREPLY,
  '__module__' : 'caas_pb2'
  # @@protoc_insertion_point(class_scope:caas.UserRegisterReply)
  })
_sym_db.RegisterMessage(UserRegisterReply)

UserInfoRequest = _reflection.GeneratedProtocolMessageType('UserInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERINFOREQUEST,
  '__module__' : 'caas_pb2'
  # @@protoc_insertion_point(class_scope:caas.UserInfoRequest)
  })
_sym_db.RegisterMessage(UserInfoRequest)

UserInfoReply = _reflection.GeneratedProtocolMessageType('UserInfoReply', (_message.Message,), {
  'DESCRIPTOR' : _USERINFOREPLY,
  '__module__' : 'caas_pb2'
  # @@protoc_insertion_point(class_scope:caas.UserInfoReply)
  })
_sym_db.RegisterMessage(UserInfoReply)



_USER = _descriptor.ServiceDescriptor(
  name='user',
  full_name='caas.user',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=426,
  serialized_end=552,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='caas.user.Register',
    index=0,
    containing_service=None,
    input_type=_USERREGISTERREQUEST,
    output_type=_USERREGISTERREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Info',
    full_name='caas.user.Info',
    index=1,
    containing_service=None,
    input_type=_USERINFOREQUEST,
    output_type=_USERINFOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['user'] = _USER


_CURL = _descriptor.ServiceDescriptor(
  name='curl',
  full_name='caas.curl',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=554,
  serialized_end=668,
  methods=[
  _descriptor.MethodDescriptor(
    name='Enqueue',
    full_name='caas.curl.Enqueue',
    index=0,
    containing_service=None,
    input_type=_ENQUEUEREQUEST,
    output_type=_ENQUEUERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetReulst',
    full_name='caas.curl.GetReulst',
    index=1,
    containing_service=None,
    input_type=_RESULTREQUEST,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CURL)

DESCRIPTOR.services_by_name['curl'] = _CURL

# @@protoc_insertion_point(module_scope)
